<div class="page-header">
            <h1>Sticky footer with fixed navbar</h1>
        </div>
        <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>body &gt; .container</code>.</p>
        <p>Back to <a href="../sticky-footer">the default sticky footer</a> minus the navbar.</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto eligendi, recusandae odit animi beatae, voluptatibus atque delectus perspiciatis laudantium maiores molestiae illo mollitia. Praesentium delectus fugit, aperiam accusantium blanditiis maxime? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo quae asperiores officia, placeat, nostrum explicabo eaque quis odit laboriosam illo id, sunt perferendis accusantium neque repellat quos commodi ea beatae?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos molestiae, provident vero ut, harum porro? Quo asperiores ducimus ipsa dicta ipsum saepe repellendus totam deserunt, non expedita iste, possimus porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate quod quas, porro facere iste, perferendis sed ab alias veritatis vitae amet iusto dolores. Vel fugiat reiciendis quaerat. Illo, non, voluptatibus?</p>